<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        @page {
            size: 80mm auto;
            margin: 0;
        }

        body {
            width: 72mm;
            margin: 0 auto;
            font-family: monospace;
            font-size: 12px;
            color: #000;
        }

        .center {
            text-align: center;
        }

        .divider {
            border-top: 1px dashed #000;
            margin: 6px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td {
            padding: 2px 0;
        }

        td:last-child {
            text-align: right;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
        }

        .status {
            text-align: center;
            font-weight: bold;
            font-size: 14px;
            margin: 8px 0;
        }
    </style>
</head>

<body>

    <div class="center">

        <div class="title">
            {{ config('app.name') }}
        </div>

        Daily Closing Slip

        <br><br>

        Receipt :
        {{ $closure->cashRegister->receipt_no }}

    </div>

    <div class="divider"></div>

    <table>

        <tr>
            <td>Date</td>
            <td>{{ $closure->business_date->format('d M Y') }}</td>
        </tr>

        <tr>
            <td>Closed By</td>
            <td>{{ $closure->closedBy->name }}</td>
        </tr>

        <tr>
            <td>Closed At</td>
            <td>{{ $closure->closed_at->format('d M Y h:i A') }}</td>
        </tr>

    </table>

    <div class="divider"></div>

    <table>

        <tr>
            <td>Opening Cash</td>
            <td>{{ getFormattedCurrency($closure->opening_cash) }}</td>
        </tr>

        <tr>
            <td>Cash Collection</td>
            <td>{{ getFormattedCurrency($closure->cash_collection) }}</td>
        </tr>

        @if ($closure->upi_collection > 0)
            <tr>
                <td>UPI Collection</td>
                <td>{{ getFormattedCurrency($closure->upi_collection) }}</td>
            </tr>
        @endif

        <tr>
            <td>Expenses</td>
            <td>{{ getFormattedCurrency($closure->expense_amount) }}</td>
        </tr>

        <tr>
            <td>Withdraw</td>
            <td>{{ getFormattedCurrency($closure->withdraw_amount) }}</td>
        </tr>

    </table>

    <div class="divider"></div>

    <table>

        <tr>
            <td>Expected Cash</td>
            <td>{{ getFormattedCurrency($closure->expected_cash) }}</td>
        </tr>

        <tr>
            <td>Counted Cash</td>
            <td>{{ getFormattedCurrency($closure->counted_cash) }}</td>
        </tr>

        <tr>
            <td>Difference</td>
            <td>{{ getFormattedCurrency(abs($closure->difference_amount)) }}</td>
        </tr>

    </table>

    <div class="divider"></div>

    <div class="status">

        @if ($closure->isBalanced())
            BALANCED
        @elseif($closure->isShort())
            DRAWER SHORT
        @else
            DRAWER EXCESS
        @endif

    </div>

    @if ($closure->difference_reason)
        <div class="divider"></div>

        Reason

        <br>

        {{ $closure->difference_reason }}
    @endif

    @if ($closure->remarks)
        <div class="divider"></div>

        Remarks

        <br>

        {{ $closure->remarks }}
    @endif

    <div class="divider"></div>

    <div class="center">

        Generated by Laundrotrak

        <br>

        {{ now()->format('d M Y h:i A') }}

    </div>

</body>

</html>
